# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Frames for Mirrors
email: framesformirrorsllc@gmail.com
phone: 813-468-4185
description: > # this means to ignore newlines until "baseurl:"
  Boring, plain bathroom mirror? Dress your bathroom up with custom frames!
  Call today to scheduale a free estimate and choose from over 60 different frame styles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "godaddy.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
